// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM3iSBa5QQjvX7mt_cVe9zZtP8IhDox2c',
    appId: '1:838923562222:web:44a8462db4d98c6d7bd7ff',
    messagingSenderId: '838923562222',
    projectId: 'petpulse-d414c',
    authDomain: 'petpulse-d414c.firebaseapp.com',
    storageBucket: 'petpulse-d414c.firebasestorage.app',
    measurementId: 'G-W0NTP7CCZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcL9dkfv1LG3ci23Xrs_Ve5NOB2QpWims',
    appId: '1:838923562222:android:5f523052dda551037bd7ff',
    messagingSenderId: '838923562222',
    projectId: 'petpulse-d414c',
    storageBucket: 'petpulse-d414c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKXOex9mEN_vwJ81kPtOZ1kTr7bVjH9p8',
    appId: '1:838923562222:ios:7dc08fd13d3781e07bd7ff',
    messagingSenderId: '838923562222',
    projectId: 'petpulse-d414c',
    storageBucket: 'petpulse-d414c.firebasestorage.app',
    iosBundleId: 'com.tuempresa.petpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKXOex9mEN_vwJ81kPtOZ1kTr7bVjH9p8',
    appId: '1:838923562222:ios:7dc08fd13d3781e07bd7ff',
    messagingSenderId: '838923562222',
    projectId: 'petpulse-d414c',
    storageBucket: 'petpulse-d414c.firebasestorage.app',
    iosBundleId: 'com.tuempresa.petpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM3iSBa5QQjvX7mt_cVe9zZtP8IhDox2c',
    appId: '1:838923562222:web:cd3f0b9ce0c5fb457bd7ff',
    messagingSenderId: '838923562222',
    projectId: 'petpulse-d414c',
    authDomain: 'petpulse-d414c.firebaseapp.com',
    storageBucket: 'petpulse-d414c.firebasestorage.app',
    measurementId: 'G-LBG8VQ73DX',
  );
}
